HomeWork14/HomeWork14/Models/ErrorViewModel.cs
using System;

namespace HomeWork14.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HomeWork14/HomeWork14/Models/PersonModel.cs
using System;

namespace HomeWork14.Models
{
    public class PersonModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Doctor { get; set; }

        public string Time { get; set; }
        //public DateTime Time { get; set; }
    }
}

HomeWork14/HomeWork14/Controllers/HomeController.cs
using HomeWork14.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HomeWork14.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HomeWork14/HomeWork14/Controllers/VisitDoctorController.cs
using HomeWork14.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Reflection.PortableExecutable;
using System.Text.Json;

namespace HomeWork14.Controllers
{
    [TypeFilter(typeof(Middleware))]

    public class VisitDoctorController : Controller
    {
        private const string filePath = "bookingDetails.json";

        public IActionResult Index()
        {
            return View();
        }

        [Route("/booking",Name ="Booking")]
        public IActionResult Booking()
        {
            //return Content("Hello, this is booking page");

            return View("~/Views/Home/Booking.cshtml");
        }

        public ActionResult BookingPerson(PersonModel personModel)
        {
            if (!timeValid(personModel.Time))
            {
                ModelState.AddModelError("Time", "Doctor Booking time must be between 10:00 and 19:00");
                return View("Index", personModel);
            }

            List<PersonModel> personModels = loadPersonModels();

            personModels.Add(personModel);

            saveBookingDetails(personModels);

            return RedirectToAction("Index");
        }




        private bool timeValid(string time)
        {
            if(DateTime.TryParse(time, out DateTime bookingTime))
            {
                DateTime startTime = DateTime.Parse("10:00");
                DateTime finishTime = DateTime.Parse("19:00");
                return bookingTime.TimeOfDay >= startTime.TimeOfDay && bookingTime.TimeOfDay <= finishTime.TimeOfDay;
            }
            return false;
        }



        private List<PersonModel> loadPersonModels()
        {
            if(System.IO.File.Exists(filePath))
            {
                string jsonData = System.IO.File.ReadAllText(filePath);
                return JsonSerializer.Deserialize<List<PersonModel>>(jsonData);
            }
            return new List<PersonModel>();
        }

        private void saveBookingDetails(List<PersonModel> personModels)
        {
            string jsonData = JsonSerializer.Serialize(personModels);
            System.IO.File.WriteAllText(filePath, jsonData);
        }
    }
}

HomeWork14/HomeWork14/Views/Home/Booking.cshtml
@model HomeWork14.Models.PersonModel

@{
    ViewData["Title"] = "Booking Page";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Booking Page</title>
</head>
<body>
    @using (Html.BeginForm("BookingPerson", "VisitDoctor", FormMethod.Post))
    {
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th colspan="2" align="center">Doctor Booking Details</th>
            </tr>
            <tr>
                <td>FirstName: </td>
                <td>
                    @Html.TextBoxFor(m => m.FirstName)
                </td>
            </tr>
            <tr>
                <td>LastName: </td>
                <td>
                    @Html.TextBoxFor(m => m.LastName)
                </td>
            </tr>
            <tr>
                <td>Doctor: </td>
                <td>
                    @Html.TextBoxFor(m => m.Doctor)
                </td>
            </tr>
            <tr>
                <td>Time: </td>
                <td>
                    @Html.TextBoxFor(m => m.Time)
                </td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Submit" /></td>
            </tr>
        </table>
    }
</body>
</html>

HomeWork14/HomeWork14/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HomeWork14/HomeWork14/Views/Shared/BookingNotAllowed.cshtml
<h1>Booking Is Not Possible</h1>

<h3>
	sorry for this 
</h3>

HomeWork14/HomeWork14/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeWork14</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeWork14</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HomeWork14 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>